services:
  frontend:
    build:
      context: ./ashs_forum_front
      target: production-stage
  backend:
    build:
      context: ./ashs_forum_back
      target: production-stage
      args:
        WORKER: ${WORKER}