services:
  backend:
    build: ./ashs_forum_back
    volumes:
      - ./ashs_forum_back:/app
    env_file:
      - ./.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - db
    
  frontend:
    build: ./ashs_forum_front
    ports:
      - "80:80"
    env_file:
      - ./.env
  
  redis:
    image: redis:8
    restart: always
    expose:
      - "6379"
    volumes:
      - ashs_forum_redis_data:/data
  
  db:
    image: postgres:18
    restart: always
    expose:
      - "5432"
    env_file:
      ./.env
    volumes:
      - ashs_forum_db_data:/var/lib/postgresql


volumes:
  ashs_forum_redis_data:
  ashs_forum_redisinsight_data:
  ashs_forum_db_data:
